### ISSUE TITLE
Integration with Dotty

### ISSUE THREAD

**Issue by liufengyun** [liufengyun/eden#3]
Currently, it can be integrated via following options:

    dotc -Ymacros -toolcp eden.jar  test.scala

Another idea is to just put `eden.jar` in `-cp` inside `dotc`, and check the presence of the symbol `dotty.eden.Quasiquote`. If present, then macros are enabled, otherwise it's not enabled. The flag is important, because when compiler is invoked via API, eden.jar may not be in the path.

**Comment by xeno-by** [comment]
Another idea that we were discussing with @odersky back then is to ship (but not build!) eden.jar with dotty and include it on -toolcp automatically.

**Comment by xeno-by** [comment]
Speaking of the flag, do you think that we can replace it with a `Class.forName` check that verifies whether some class from Eden is on toolcp?

**Comment by liufengyun** [comment]
@xeno-by that's what in my mind, so user doesn't have to specify the flag.

**Comment by liufengyun** [comment]
For command line users using `dotc`, I don't think we have an easy solution. `dotc -toolcp eden.jar  test.scala` is not enough, as all recursive dependencies of `eden` and `scalameta` have to be available for reflection.

For SBT users, the simplest approach is to add `eden` as a dependency, that simplifies everything.

**Comment by liufengyun** [comment]
Note that currently we do need `eden` to be in `classpath` because the two methods `apply` and `unapply` defined here:
https://github.com/liufengyun/eden/blob/master/src/main/scala/meta/eden/quasiquote/Quote.scala#L43

**Comment by xeno-by** [comment]
Can you submit these two helpers to an internal package in scalameta? E.g. somewhere around https://github.com/xeno-by/scalameta/blob/master/scalameta/trees/src/main/scala/scala/meta/internal/ast/Helpers.scala.

**Comment by liufengyun** [comment]
Now the solution for integration is simple:

1. for command line, use `sbt-assembly` bundled jar, and add it to `-classpath` (thanks @xeno-by )
2. for sbt, just add `eden` as dependency

It seems to me this suffices for now.
