### ISSUE TITLE
Support type parameters in def macros

### ISSUE THREAD

**Issue by liufengyun** [liufengyun/eden#4]
The transform should take type parameters into consideration and handle PolyType.

**Comment by liufengyun** [comment]
It seems inlining makes this feature difficult to implement without sacrificing type safety.

Given the macro definition:

```Scala
class eden {
  inline def as[T](a: Any): T = meta {
    q"$a.asInstanceOf[$tp]"
  }
}
```

We transform it into the follows:

```Scala
class eden {
  inline def as[T](a: Any): T = meta { eden$inline.as(this)(a) }    //   <= how to pass T?
}

object eden$inline {
  def as(prefix: scala.meta.Term)(T: scala.meta.Type)(a: scala.meta.Term): scala.meta.Tree = {
    q"$a.asInstanceOf[$T]"
  }
}
```

But in the meta block above, how do we pass `T` to the implementation, so that inlining & type safety are not compromised?

Note that without `inlining`, we don't face this problem, as we don't have the call `eden$inline.as(this)(a)` as part of the code.

**Comment by liufengyun** [comment]
Type parameters are supported in e9e392bac516612ccca6b44057f2937ed61f8373. I ended up doing away with the complication of inlining. I resort to a special flag `macro` to tell whether to expand a macro or not. https://github.com/liufengyun/dotty/commit/ef16d23360e075b3e23db99158d62859a55526dd

It seems we can implement macros much simpler without inlining. Inlining is itself another category of useful macros with better foundation. Mix them together seems to make both harder.

**Comment by xeno-by** [comment]
Am I right in thinking that you only support meta blocks that are the sole right-hand sides of inline methods (by translating such methods into `<macro>` something)?

**Comment by liufengyun** [comment]
Yes, the translation is the same before, except we remove the `inline` flag and add `macro` flag, to avoid inlining.

I don't know how to translate meta blocks that are in the middle of an expression and reflectively expand such meta blocks.

**Comment by liufengyun** [comment]
Improvement of typing to avoid `asInstanceOf` boilerplate is now implemented in https://github.com/liufengyun/dotty/commit/26ee23a1624e728da761506775caf7b2559ef187 and https://github.com/liufengyun/eden/commit/acc43d3f9b6f451ca3edb34ec05812d483248e99 .

**Comment by liufengyun** [comment]
Close this for now.
